CREATE TABLE bank_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    active BOOLEAN NOT NULL
);

CREATE TABLE account
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    current_amount NUMERIC(18, 4) NOT NULL,
    active BOOLEAN NOT NULL
);


CREATE TABLE ledger
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type VARCHAR(32) NOT NULL,
    account_id BIGINT NOT NULL,
    amount NUMERIC(18, 4),
    currency VARCHAR(3) NOT NULL,
    transaction_uuid UUID NOT NULL,
    created_at TIMESTAMP NOT NULL
);


CREATE INDEX idx_account_user_id ON account(user_id);
CREATE INDEX idx_ledger_account_id ON ledger(account_id);